apiVersion: v1
kind: Service
metadata:
  name: nanoca-server
  namespace: security-infra
  labels:
    app: nanoca-server
spec:
  selector:
    app: nanoca-server
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  type: ClusterIP
